"""Constantes de integridade referencial e dominio para o modelo ORM."""

# ON DELETE — nenhuma FK permite perda de historico operacional.
ON_DELETE_RESTRICT = "RESTRICT"
ON_DELETE_SET_NULL = "SET NULL"

# Categorias de auditoria (evento_auditoria.categoria)
AUDIT_CATEGORIA_AUTH = "AUTH"
AUDIT_CATEGORIA_XML = "XML"
AUDIT_CATEGORIA_CARREGAMENTO = "CARREGAMENTO"
AUDIT_CATEGORIA_USUARIO = "USUARIO"
AUDIT_CATEGORIA_SISTEMA = "SISTEMA"

# Eventos de auditoria (evento_auditoria.evento)
AUDIT_EVENTO_LOGIN = "LOGIN"
AUDIT_EVENTO_LOGOUT = "LOGOUT"
AUDIT_EVENTO_IMPORTACAO_XML = "IMPORTACAO_XML"
AUDIT_EVENTO_FINALIZACAO_CARREGAMENTO = "FINALIZACAO_CARREGAMENTO"
AUDIT_EVENTO_PRIMEIRA_IMPRESSAO = "PRIMEIRA_IMPRESSAO"
AUDIT_EVENTO_REIMPRESSAO = "REIMPRESSAO"
AUDIT_EVENTO_REENTREGA = "REENTREGA"
AUDIT_EVENTO_ENTREGA_BALCAO = "ENTREGA_BALCAO"
AUDIT_EVENTO_COMPLEMENTACAO = "COMPLEMENTACAO"
AUDIT_EVENTO_ALTERACAO_USUARIO = "ALTERACAO_USUARIO"
AUDIT_EVENTO_RETENCAO_DADOS = "RETENCAO_DADOS"
AUDIT_EVENTO_CAPACIDADE_ALERTA = "CAPACIDADE_ALERTA"

# Eventos de historico operacional (historico_operacional.evento)
HISTORICO_EVENTO_FINALIZACAO = "FINALIZACAO"
HISTORICO_EVENTO_REENTREGA = "REENTREGA"
HISTORICO_EVENTO_ENTREGA_BALCAO = "ENTREGA_BALCAO"
HISTORICO_EVENTO_COMPLEMENTACAO = "COMPLEMENTACAO"

# Tipos de documento (documento.tipo)
DOC_TIPO_MINUTA = "MINUTA"
DOC_TIPO_ROMANEIO = "ROMANEIO"

# Tipos de valor em configuracao.tipo_valor
CONFIG_TIPO_STRING = "STRING"
CONFIG_TIPO_JSON = "JSON"
CONFIG_TIPO_INTEGER = "INTEGER"
CONFIG_TIPO_BOOLEAN = "BOOLEAN"
