"""
Chaves substitutas (surrogate keys) do dominio Minuta.

Integer + autoincrement=True gera IDs nativamente em:
- SQLite: INTEGER PRIMARY KEY AUTOINCREMENT (ROWID alias)
- PostgreSQL: SERIAL / GENERATED BY DEFAULT AS IDENTITY

BigInteger nao autoincrementa no SQLite; o volume operacional interno
nao exige 64 bits — Integer (ate ~2.1bi) e suficiente para todas as tabelas.
"""

from sqlalchemy import Integer

SurrogateKey = Integer
